# =========================================================================
# System libraries
# =========================================================================

project(sys)

# =========================================================================

add_subdirectory(kernel)

# =========================================================================
