FROM silkeh/clang AS base

ARG CONFIG=x86_64

RUN apt update
RUN apt upgrade -y

RUN apt install -y cmake
RUN apt install -y grub-pc-bin grub-common xorriso

COPY src /src

WORKDIR /work

RUN cmake ../src -DCONFIG=${CONFIG}

RUN cmake --build . -v
RUN cmake --install . -v

RUN grub-mkrescue -o boot.iso sysroot

FROM scratch AS output
COPY --from=base /work/boot.iso /
COPY --from=base /work/sys/kernel/kernel.elf /kernel.elf
