# =========================================================================
# System libraries
# =========================================================================

project(libs)

# =========================================================================

add_subdirectory(libk)
add_subdirectory(libkpp)

# =========================================================================
